url: https://pubinv.github.io/turret-joint
repourl: https://github.com/PubInv/turret-joint
projecttitle: "The Turret Joint"
featuretitle: "Public Invention"
featurelink: https://pubinv.github.io/PubInv